language: julia

julia:
  - 1.0
  - 1.5
  - 1.6
  - nightly

os:
  - linux
  - osx
  - windows
  
jobs:
  allow_failures:
    - julia: nightly
    - julia: 1.6

notifications:
  email: false
  
after_success:
  - julia -e 'import PointLib; cd(joinpath(dirname(pathof(PointLib)), "..")); using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
