name = "PointLib"
uuid = "7de1f589-fb91-4994-b265-ccfc43c44ada"
authors = ["Sambit Kumar Dash <sambitdash@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
